### ISSUE TITLE
REVAMP OF THE LANDING PAGE OF https://nrnb.org/

### ISSUE THREAD

**Issue by Swapnendu003** [nrnb/gsoc2024_projects#1]
**Description:**

1. Redesigned the landing page to enhance visual appeal and user experience.
2. Updated layout, and styling for better responsiveness and modern aesthetics.
![image](https://github.com/user-attachments/assets/adc80d88-039b-481f-9a12-ca8a0fa43927)

**If I get the chance to contribute to the Project it will be a great opportunity for me**

**Comment by khanspers** [comment]
No updates are being made or accepted at this time, as part of GSoC or otherwise. Closing.

**Comment by Swapnendu003** [comment]
Will NRNB take part in GSoC at this time? I will be glad if I get a chance to contribute.

**Comment by khanspers** [comment]
NRNB will apply for GSoC 2025 (assuming it is happening, it has not been announced yet), but that does not guarantee we will be selected as a mentoring organization. NRNB GSoC projects will be organized here: https://github.com/nrnb/GoogleSummerOfCode
